=== vishalaureate/hello-world/etc/adminactivity.xsd
<?xml version="1.0" ?>
<!--
/**
 * KiwiCommerce
 *
 * Do not edit or add to this file if you wish to upgrade to newer versions in the future.
 * If you wish to customize this module for your needs.
 * Please contact us https://kiwicommerce.co.uk/contacts.
 *
 * @category   KiwiCommerce
 * @package    KiwiCommerce_AdminActivity
 * @copyright  Copyright (C) 2018 Kiwi Commerce Ltd (https://kiwicommerce.co.uk/)
 * @license    https://kiwicommerce.co.uk/magento2-extension-license/
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:all>
                <xs:element name="actions" type="adminActions" minOccurs="0" />
                <xs:element name='modules'  type="adminModules" minOccurs="1" />
            </xs:all>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="adminActions">
        <xs:sequence>
            <xs:element name="action" type="adminAction" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="adminAction">
        <xs:sequence>
            <xs:element name="label" type="actionLabel" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
        <xs:attribute name="id" type="xs:ID" use="required"/>
    </xs:complexType>
    <xs:complexType name="adminModules">
        <xs:sequence>
            <xs:element name="module" type="adminModule" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="adminModule">
        <xs:all>
            <xs:element name="label" type="actionLabel" minOccurs="0" maxOccurs="1" />
            <xs:element name="models" type="modelClass" minOccurs="0" />
            <xs:element name="events" type="modelEvents" minOccurs="0" />
            <xs:element name="config" type="configEvents" minOccurs="0" />
        </xs:all>
        <xs:attribute name="name" type="xs:token" use="required"/>
    </xs:complexType>
    <xs:complexType name="actionLabel">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="translate" use="optional" fixed="true" type="xs:boolean"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    <xs:complexType name="modelClass">
        <xs:sequence>
            <xs:element name="class" type="className" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="modelEvents">
        <xs:sequence>
            <xs:element name="event" type="eventType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="configEvents">
        <xs:sequence>
            <xs:element name="trackfield" type="classMethod" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="configpath" type="modelConstant" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="editurl" type="editurl" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="itemfield" type="field" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="classMethod">
        <xs:attribute name="method" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="modelConstant">
        <xs:attribute name="constant" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="editurl">
        <xs:attribute name="url" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="field">
        <xs:attribute name="field" type="xs:string" use="required"/>
    </xs:complexType>
    <xs:complexType name="eventType">
        <xs:attribute name="controller_action" type="xs:token" use="required" />
        <xs:attribute name="action_alias" type="xs:token" use="required" />
        <xs:attribute name="post_dispatch" type="xs:token" />
    </xs:complexType>
    <xs:complexType name="className">
        <xs:attribute name="name" type="xs:token" use="required" />
    </xs:complexType>
</xs:schema>

=== vishalaureate/hello-world/etc/adminactivity.xml
<?xml version="1.0" ?>
<!--
/**
 * KiwiCommerce
 *
 * Do not edit or add to this file if you wish to upgrade to newer versions in the future.
 * If you wish to customize this module for your needs.
 * Please contact us https://kiwicommerce.co.uk/contacts.
 *
 * @category   KiwiCommerce
 * @package    KiwiCommerce_AdminActivity
 * @copyright  Copyright (C) 2018 Kiwi Commerce Ltd (https://kiwicommerce.co.uk/)
 * @license    https://kiwicommerce.co.uk/magento2-extension-license/
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="adminactivity.xsd">
    <actions>
        <action id="view">
            <label translate="true">View</label>
        </action>
        <action id="save">
            <label translate="true">New</label>
        </action>
        <action id="edit">
            <label translate="true">Edit</label>
        </action>
        <action id="delete">
            <label translate="true">Delete</label>
        </action>
        <action id="massDelete">
            <label translate="true">Mass Delete</label>
        </action>
        <action id="massStatus">
            <label translate="true">Mass Status</label>
        </action>
        <action id="massEdit">
            <label translate="true">Mass Edit</label>
        </action>
        <action id="massSubscribe">
            <label translate="true">Mass Subscribe</label>
        </action>
        <action id="massUnsubscribe">
            <label translate="true">Mass Unsubscribe</label>
        </action>
        <action id="massAssignGroup">
            <label translate="true">Mass Assign Group</label>
        </action>
        <action id="massDisable">
            <label translate="true">Mass Disable</label>
        </action>
        <action id="massEnable">
            <label translate="true">Mass Enable</label>
        </action>
        <action id="reorder">
            <label translate="true">Reorder</label>
        </action>
        <action id="hold">
            <label translate="true">Hold</label>
        </action>
        <action id="unhold">
            <label translate="true">Unhold</label>
        </action>
        <action id="cancel">
            <label translate="true">Cancel</label>
        </action>
        <action id="addComment">
            <label translate="true">Add Comment</label>
        </action>
        <action id="massCancel">
            <label translate="true">Mass Cancel</label>
        </action>
        <action id="massHold">
            <label translate="true">Mass Hold</label>
        </action>
        <action id="massUnhold">
            <label translate="true">Mass Unhold</label>
        </action>
        <action id="assign">
            <label translate="true">Assign</label>
        </action>
        <action id="unassign">
            <label translate="true">Unassign</label>
        </action>
    </actions>
    <modules>
        <module name="catalog_products">
            <label translate="true">Catalog Product</label>
            <models>
                <class name="Magento\Catalog\Model\Product" />
                <class name="Magento\Catalog\Model\Product\Action" />
                <class name="Magento\Catalog\Model\Product\Attribute\Source\Status" />
                <class name="Magento\CatalogInventory\Model\StockState" />
            </models>
            <events>
                <event controller_action="catalog_product_save" action_alias="save" />
                <event controller_action="catalog_product_massDelete" action_alias="massDelete" />
                <event controller_action="catalog_product_massStatus" action_alias="massStatus" post_dispatch="productUpdate" />
                <event controller_action="catalog_product_action_attribute_save" action_alias="massEdit" post_dispatch="productUpdate" />
            </events>
            <config>
                <trackfield method="getProductFieldData" />
                <configpath constant="MODULE_PRODUCT" />
                <editurl url="{{module}}/{{controller}}/edit/id/{{id}}" />
                <itemfield field="name" />
            </config>
        </module>
        <module name="catalog_categories">
            <label translate="true">Catalog Categories</label>
            <models>
                <class name="Magento\Catalog\Model\Category" />
            </models>
            <events>
                <event controller_action="catalog_category_save" action_alias="save" />
                <event controller_action="catalog_category_edit" action_alias="edit" />
                <event controller_action="catalog_category_delete" action_alias="delete" />
            </events>
            <config>
                <trackfield method="getCategoryFieldData" />
                <configpath constant="MODULE_CATEGORY" />
                <editurl url="{{module}}/{{controller}}/edit/id/{{id}}" />
                <itemfield field="name" />
            </config>
        </module>
        <module name="customer">
            <label translate="true">Customer</label>
            <models>
                <class name="Magento\Customer\Model\Customer" />
                <class name="Magento\Newsletter\Model\Subscriber" />
                <class name="Magento\Customer\Model\Address" />
            </models>
            <events>
                <event controller_action="customer_index_save" action_alias="save" />
                <event controller_action="customer_index_delete" action_alias="delete" />
                <event controller_action="customer_index_massDelete" action_alias="massDelete" />
                <event controller_action="customer_index_massSubscribe" action_alias="massSubscribe" />
                <event controller_action="customer_index_massUnsubscribe" action_alias="massUnsubscribe" />
                <event controller_action="customer_index_massAssignGroup" action_alias="massAssignGroup" />
                <event controller_action="customer_index_inlineEdit" action_alias="massEdit" />
            </events>
            <config>
                <trackfield method="getCustomerFieldData" />
                <configpath constant="MODULE_CUSTOMER" />
                <editurl url="{{module}}/{{controller}}/edit/id/{{id}}" />
                <itemfield field="firstname" />
            </config>
        </module>
        <module name="customer_group">
            <label translate="true">Customer Group</label>
            <models>
                <class name="Magento\Customer\Model\Group" />
            </models>
            <events>
                <event controller_action="customer_group_save" action_alias="save" />
                <event controller_action="customer_group_delete" action_alias="delete" />
            </events>
            <config>
                <trackfield method="getCustomerGroupFieldData" />
                <configpath constant="MODULE_CUSTOMER" />
                <editurl url="{{module}}/{{controller}}/edit/id/{{id}}" />
                <itemfield field="customer_group_code" />
            </config>
        </module>
        <module name="catalog_promotion">
            <label translate="true">Catalog Promotion</label>
            <models>
                <class name="Magento\CatalogRule\Model\Rule" />
            </models>
            <events>
                <event controller_action="catalog_rule_promo_catalog_save" action_alias="save" />
                <event controller_action="catalog_rule_promo_catalog_edit" action_alias="edit" />
                <event controller_action="catalog_rule_promo_catalog_delete" action_alias="delete" />
            </events>
            <config>
                <trackfield method="getCatalogPromotionFieldData" />
                <configpath constant="MODULE_PROMOTION" />
                <editurl url="{{module}}/{{controller}}/edit/id/{{id}}" />
                <itemfield field="name" />
            </config>
        </module>
        <module name="cart_promotion">
            <label translate="true">Cart Promotion</label>
            <models>
                <class name="Magento\SalesRule\Model\Rule" />
            </models>
            <events>
                <event controller_action="sales_rule_promo_quote_save" action_alias="save" />
                <event controller_action="sales_rule_promo_quote_edit" action_alias="edit" />
                <event controller_action="sales_rule_promo_quote_delete" action_alias="delete" />
            </events>
            <config>
                <trackfield method="getCartPromotionFieldData" />
                <configpath constant="MODULE_PROMOTION" />
                <editurl url="{{module}}/{{controller}}/edit/id/{{id}}" />
                <itemfield field="name" />
            </config>
        </module>
        <module name="email">
            <label translate="true">Email Newsletter</label>
            <models>
                <class name="Magento\Email\Model\Template" />
                <class name="Magento\Newsletter\Model\Template" />
            </models>
            <events>
                <event controller_action="adminhtml_email_template_save" action_alias="save" />
                <event controller_action="adminhtml_email_template_edit" action_alias="edit" />
                <event controller_action="adminhtml_email_template_delete" action_alias="delete" />
                <event controller_action="newsletter_template_save" action_alias="save" />
                <event controller_action="newsletter_template_delete" action_alias="delete" />
            </events>
            <config>
                <trackfield method="getEmailFieldData" />
                <configpath constant="MODULE_EMAIL" />
                <editurl url="{{module}}/{{controller}}/edit/id/{{id}}" />
                <itemfield field="template_subject" />
            </config>
        </module>
        <module name="cms_pages">
            <label translate="true">Cms Pages</label>
            <models>
